server:
  port: 8080
  compression:
    enabled: true
spring:
  application:
    name: digitalmemo
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=digitalmemo
    username: sa
    password: root
  jmx:
    default-domain: digitalmemo
  thymeleaf:
    enabled: true
    check-template-location: true
    prefix: classpath:/webapp/
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml

